### PR TITLE
Fix comments

### LINKED ISSUE #69: Motivate why bugs, PMD or checkstyles have been left in the code.

### PR DESCRIPTION
**Pull request by jimhommes**
This fixes the comments by the TA on PMD and checkstyle. 

Fixes #69.

Increased the CycloComplexity rate because these 'collision' functions simply have to check all these cases.
Increased method count for a class because only the level Controller simply needs all these methods, and they 'belong' there. Not messy.
Increased parameter count because they're needed in the SpriteBase class and evolve down to a couple more. Pretty basic. 

Fixed all other errors and added JavaDoc

### CODE REVIEW

**Comment by LilideBree** [comment]
Update in ScreenController doesn't have a javadoc.

**Comment by LilideBree** [comment]
In bubble, it needs to be explained why 8 parameters are used.

**Comment by LilideBree** [comment]
GravityObject, the attribute doesn't have a javadoc.

**Comment by LilideBree** [comment]
Does the override in Input need a javadoc?

File: src/main/java/controller/LevelController.java [hunk 1]
```diff
@@ -31,6 +32,12 @@
...
  */
+
+/**
+ * This is the level controller.
+ * Here all the interactions with the level happens.
+ * It's kind of the main controller.
+ */
 public class LevelController implements Initializable {
 
     /**
```
Comment (LilideBree) [inline src/main/java/controller/LevelController.java:43]: ArrayList checkstyle error should be explained here in the comment.

File: src/main/java/controller/ScreenController.java [hunk 2]
```diff
@@ -14,6 +14,11 @@
...
  * @since 9/11/2015
  */
+
+/**
+ * This is the Screen Controller, which handles all GUI interactions.
+ * If there is a change in coordinates, this controller draws it on the screen.
+ */
 public class ScreenController {
 
     private ArrayList<SpriteBase> sprites;
```
Comment (LilideBree) [inline src/main/java/controller/ScreenController.java:27]: Should these also have a javadoc comment?

Comment (LilideBree) [inline src/main/java/controller/ScreenController.java:27]: Also the update in this class doesn't have a javadoc comment.

**Comment by LilideBree** [comment]
The arrayLists need to be explained in Level, I know that you explained them in the pull request, but in the code it needs to be obvious why it has been used.

**Comment by LilideBree** [comment]
Player is also missing javadoc on the attributes. I can't add a comment to a class that hasn't been changed, as far as I'm aware.

File: src/main/java/model/Settings.java [hunk 3]
```diff
@@ -1,9 +1,9 @@
 package model;
 
 /**
- * Created by Matthijs on 03-09-15.
+ * Class used for storing default settings.
  */
-public class Settings {
+public final class Settings {
 
     public static final double SCENE_WIDTH = 832;
```
Comment (LilideBree) [inline src/main/java/model/Settings.java:11]: Do all these also need javadocs?
